env:
  - MAVEN_VERSION=3.2.5
install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"
script: "./mvnw --show-version --errors --batch-mode -Prun-its clean verify"
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: angular2project1


