env:
  - MAVEN_VERSION=3.2.5
  - MAVEN_VERSION=3.3.9
install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"
script: "./mvnw --show-version --errors --batch-mode -Prun-its clean verify"
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: lippep-spring-boot-test
